In [2]:
import pandas as pd

# Mostrar los primeros 5 registros
#print(data.head())
def cambiar_delimitador(contenido):
    return contenido.replace(",", "\t")

with open("Catalog_v2.csv", "r") as file:
    contenido = file.read()

contenido_modificado = cambiar_delimitador(contenido)

with open("Catalog_v2_modificado.csv", "w") as file:
    file.write(contenido_modificado)

print("El archivo ha sido modificado y guardado como Catalog_v2_modificado.csv")

print(contenido_modificado)

df = pd.read_csv("Catalog_v2_modificado.csv", sep = '\t')

df

El archivo ha sido modificado y guardado como Catalog_v2_modificado.csv
﻿levelType	code	catalogType	name	description	sourceLink
CATEGORY	Street Lighting	PRODUCT	Street Lighting	Category code for Street Lighting	http://lighttree.com/Street Lighting
CATEGORY	Pedestrian Lighting	PRODUCT	Pedestrian Lighting	Category code for Pedestrian Lighting	http://lighttree.com/Pedestrian Lighting
CATEGORY	Traffic Signal Poles	PRODUCT	Traffic Signal Poles	Category code for Traffic Signal Poles	http://lighttree.com/Traffic Signal Poles
CATEGORY	Controls	PRODUCT	Controls	Category code for Controls	http://lighttree.com/Controls
CATEGORY	Downlights	PRODUCT	Downlights	Category code for Downlights	http://lighttree.com/Downlights
CATEGORY	Retrofit Downlights	PRODUCT	Retrofit Downlights	Category code for Retrofit Downlights	http://lighttree.com/Retrofit Downlights
CATEGORY	Ambient	PRODUCT	Ambient	Category code for Ambient	http://lighttree.com/Ambient
CATEGORY	Bulbs	PRODUCT	Bulbs	Category code for Bulbs	http://lighttree.com/Bulbs
CATEGORY	Controllers	PRODUCT	Controllers	Category code for Controllers	http://lighttree.com/Controllers
CATEGORY	Enclosures	PRODUCT	Enclosures	Category code for Enclosures	http://lighttree.com/Enclosures
CATEGORY	High Voltage Electrical	PRODUCT	High Voltage Electrical	Category code for High Voltage Electrical	http://lighttree.com/High Voltage Electrical
CATEGORY	Lenses	PRODUCT	Lenses	Category code for Lenses	http://lighttree.com/Lenses
CATEGORY	Luminaire	PRODUCT	Luminaire	Category code for Luminaire	http://lighttree.com/Luminaire
CATEGORY	Mechanicals	PRODUCT	Mechanicals	Category code for Mechanicals	http://lighttree.com/Mechanicals
CATEGORY	Primary Chassis	PRODUCT	Primary Chassis	Category code for Primary Chassis	http://lighttree.com/Primary Chassis
CATEGORY	Primary Foundation	PRODUCT	Primary Foundation	Category code for Primary Foundation	http://lighttree.com/Primary Foundation
CATEGORY	Secondary Chassis	PRODUCT	Secondary Chassis	Category code for Secondary Chassis	http://lighttree.com/Secondary Chassis
BRAND	Public Sector	PRODUCT	Public Sector	Brand code for Public Sector	http://lighttree.com/Public Sector
BRAND	Commercial	PRODUCT	Commercial	Brand code for Commercial	http://lighttree.com/Commercial
FAMILY	Alliance	PRODUCT	Alliance	Family code for Alliance	http://lighttree.com/Alliance
FAMILY	Helm	PRODUCT	Helm	Family code for Helm	http://lighttree.com/Helm
FAMILY	Flatbush Avenue	PRODUCT	Flatbush Avenue	Family code for Flatbush Avenue	http://lighttree.com/Flatbush Avenue
FAMILY	Bishops Crook	PRODUCT	Bishops Crook	Family code for Bishops Crook	http://lighttree.com/Bishops Crook
FAMILY	City Light	PRODUCT	City Light	Family code for City Light	http://lighttree.com/City Light
FAMILY	LED Type E	PRODUCT	LED Type E	Family code for LED Type E	http://lighttree.com/LED Type E
FAMILY	All	PRODUCT	All	Family code for All	http://lighttree.com/All
FAMILY	Cobra Head	PRODUCT	Cobra Head	Family code for Cobra Head	http://lighttree.com/Cobra Head
FAMILY	Stad	PRODUCT	Stad	Family code for Stad	http://lighttree.com/Stad
FAMILY	Fulton	PRODUCT	Fulton	Family code for Fulton	http://lighttree.com/Fulton
FAMILY	Flushing Meadows	PRODUCT	Flushing Meadows	Family code for Flushing Meadows	http://lighttree.com/Flushing Meadows
FAMILY	World’s Fair	PRODUCT	World’s Fair	Family code for World’s Fair	http://lighttree.com/World’s Fair
FAMILY	Round Top Head	PRODUCT	Round Top Head	Family code for Round Top Head	http://lighttree.com/Round Top Head
FAMILY	All	PRODUCT	All	Family code for All	http://lighttree.com/All
FAMILY	Type M–2 Traffic Signal Pole	PRODUCT	Type M–2 Traffic Signal Pole	Family code for Type M–2 Traffic Signal Pole	http://lighttree.com/Type M–2 Traffic Signal Pole
FAMILY	Alliance Traffic Signal Pole	PRODUCT	Alliance Traffic Signal Pole	Family code for Alliance Traffic Signal Pole	http://lighttree.com/Alliance Traffic Signal Pole
FAMILY	All	PRODUCT	All	Family code for All	http://lighttree.com/All
FAMILY	Ventura	PRODUCT	Ventura	Family code for Ventura	http://lighttree.com/Ventura
FAMILY	Northridge 	PRODUCT	Northridge 	Family code for Northridge 	http://lighttree.com/Northridge
FAMILY	Miramar 	PRODUCT	Miramar 	Family code for Miramar 	http://lighttree.com/Miramar
FAMILY	Tulare	PRODUCT	Tulare	Family code for Tulare	http://lighttree.com/Tulare
FAMILY	Alameda	PRODUCT	Alameda	Family code for Alameda	http://lighttree.com/Alameda
FAMILY	Alpine	PRODUCT	Alpine	Family code for Alpine	http://lighttree.com/Alpine
FAMILY	Imperial 	PRODUCT	Imperial 	Family code for Imperial 	http://lighttree.com/Imperial
FAMILY	Sunset 	PRODUCT	Sunset 	Family code for Sunset 	http://lighttree.com/Sunset
FAMILY	Riverside	PRODUCT	Riverside	Family code for Riverside	http://lighttree.com/Riverside
FAMILY	Buccaneer 	PRODUCT	Buccaneer 	Family code for Buccaneer 	http://lighttree.com/Buccaneer
FAMILY	Santa Cruz 	PRODUCT	Santa Cruz 	Family code for Santa Cruz 	http://lighttree.com/Santa Cruz
FAMILY	Stinson 	PRODUCT	Stinson 	Family code for Stinson 	http://lighttree.com/Stinson
LINE	Rural	PRODUCT	Rural	Line code for Rural	http://lighttree.com/Rural
LINE	City	PRODUCT	City	Line code for City	http://lighttree.com/City
LINE	Special application	PRODUCT	Special application	Line code for Special application	http://lighttree.com/Special application
LINE	Traffic	PRODUCT	Traffic	Line code for Traffic	http://lighttree.com/Traffic
CATEGORY	Bulbs	ITEM	Bulbs	Category code for Bulbs	http://lighttree.com/Bulbs
CATEGORY	Controllers	ITEM	Controllers	Category code for Controllers	http://lighttree.com/Controllers
CATEGORY	Enclosures	ITEM	Enclosures	Category code for Enclosures	http://lighttree.com/Enclosures
CATEGORY	High Voltage Electrical	ITEM	High Voltage Electrical	Category code for High Voltage Electrical	http://lighttree.com/High Voltage Electrical
CATEGORY	Lenses	ITEM	Lenses	Category code for Lenses	http://lighttree.com/Lenses
CATEGORY	Luminaire	ITEM	Luminaire	Category code for Luminaire	http://lighttree.com/Luminaire
CATEGORY	Mechanicals	ITEM	Mechanicals	Category code for Mechanicals	http://lighttree.com/Mechanicals
CATEGORY	Primary Chassis	ITEM	Primary Chassis	Category code for Primary Chassis	http://lighttree.com/Primary Chassis
CATEGORY	Primary Foundation	ITEM	Primary Foundation	Category code for Primary Foundation	http://lighttree.com/Primary Foundation
CATEGORY	Secondary Chassis	ITEM	Secondary Chassis	Category code for Secondary Chassis	http://lighttree.com/Secondary Chassis

,levelType,code,catalogType,name,description,sourceLink
0,CATEGORY,Street Lighting,PRODUCT,Street Lighting,Category code for Street Lighting,http://lighttree.com/Street Lighting
1,CATEGORY,Pedestrian Lighting,PRODUCT,Pedestrian Lighting,Category code for Pedestrian Lighting,http://lighttree.com/Pedestrian Lighting
2,CATEGORY,Traffic Signal Poles,PRODUCT,Traffic Signal Poles,Category code for Traffic Signal Poles,http://lighttree.com/Traffic Signal Poles
3,CATEGORY,Controls,PRODUCT,Controls,Category code for Controls,http://lighttree.com/Controls
4,CATEGORY,Downlights,PRODUCT,Downlights,Category code for Downlights,http://lighttree.com/Downlights
...,...,...,...,...,...,...
57,CATEGORY,Luminaire,ITEM,Luminaire,Category code for Luminaire,http://lighttree.com/Luminaire
58,CATEGORY,Mechanicals,ITEM,Mechanicals,Category code for Mechanicals,http://lighttree.com/Mechanicals
59,CATEGORY,Primary Chassis,ITEM,Primary Chassis,Category code for Primary Chassis,http://lighttree.com/Primary Chassis
60,CATEGORY,Primary Foundation,ITEM,Primary Foundation,Category code for Primary Foundation,http://lighttree.com/Primary Foundation
61,CATEGORY,Secondary Chassis,ITEM,Secondary Chassis,Category code for Secondary Chassis,http://lighttree.com/Secondary Chassis

In [5]:
data1 = pd.DataFrame({
    'ID': [1,2,3,4],
    'Nombre': ['Ana', 'Luis', 'Juan', 'Alberto']
})

data2 = pd.DataFrame({
    'ID': [3,4,5],
    'Salario': ['20000', '25000', '30000']
})

# Fusión de ambos DataFrames por la columna 'ID' (común)
data_merged_inner = pd.merge(data1, data2, how='inner', on='ID')

print(data_merged_inner, "\n")

data_merged_outer = pd.merge(data1, data2, how='outer', on='ID')

print(data_merged_outer)
#groupById = data_merged.groupby('ID')

#print(groupById)

   ID   Nombre Salario
0   3     Juan   20000
1   4  Alberto   25000

   ID   Nombre Salario
0   1      Ana     NaN
1   2     Luis     NaN
2   3     Juan   20000
3   4  Alberto   25000
4   5      NaN   30000

In [ ]:
df1 = pd.DataFrame({
    'ID_cliente': [1,2,3,4,5]
})

df2 = pd.DataFrame({
    'ID_usuario': [1,2,3,4,5]
})

df_merged = pd.merge(df1, df2, how='inner', left_on='ID_cliente', right_on='ID_usuario')

   ID_cliente  ID_usuario
0           1           1
1           2           2
2           3           3
3           4           4
4           5           5

In [9]:
from tabulate import tabulate

print(tabulate(df_merged, headers=["ID_cliente", "ID_usuario"], tablefmt='orgtbl'))

|    |   ID_cliente |   ID_usuario |
|----+--------------+--------------|
|  0 |            1 |            1 |
|  1 |            2 |            2 |
|  2 |            3 |            3 |
|  3 |            4 |            4 |
|  4 |            5 |            5 |

In [21]:
from sklearn.datasets import load_breast_cancer

# Cargar el dataset
data = load_breast_cancer()
df = pd.DataFrame(data.data, columns=data.feature_names)

# Añadir la columna 'target' (maligno o benigno)
df['target'] = data.target

# Mostrar las primeras filas para ver cómo está estructurado el DataFrame

df_modified = df['mean radius'] + df['mean texture']

df_final = pd.DataFrame(df_modified)

print(tabulate(df_final, headers=["mean radius", "mean tecture"], tablefmt='orgtbl'))

|   mean radius |   mean tecture |
|---------------+----------------|
|             0 |         28.37  |
|             1 |         38.34  |
|             2 |         40.94  |
|             3 |         31.8   |
|             4 |         34.63  |
|             5 |         28.15  |
|             6 |         38.23  |
|             7 |         34.54  |
|             8 |         34.82  |
|             9 |         36.5   |
|            10 |         39.26  |
|            11 |         33.67  |
|            12 |         43.97  |
|            13 |         39.8   |
|            14 |         36.34  |
|            15 |         42.08  |
|            16 |         34.81  |
|            17 |         36.81  |
|            18 |         41.96  |
|            19 |         27.9   |
|            20 |         28.79  |
|            21 |         21.944 |
|            22 |         29.6   |
|            23 |         44.2   |
|            24 |         38.03  |
|            25 |         33.54  |
|            26 |         36.11  |
|            27 |         38.86  |
|            28 |         40.57  |
|            29 |         32.62  |
|            30 |         43.74  |
|            31 |         30.54  |
|            32 |         41     |
|            33 |         45.74  |
|            34 |         34.01  |
|            35 |         38.33  |
|            36 |         35.97  |
|            37 |         31.45  |
|            38 |         40.19  |
|            39 |         34.3   |
|            40 |         35.02  |
|            41 |         32.3   |
|            42 |         43.88  |
|            43 |         33.56  |
|            44 |         34.98  |
|            45 |         36.25  |
|            46 |         25.036 |
|            47 |         31.83  |
|            48 |         26.68  |
|            49 |         35.79  |
|            50 |         33.36  |
|            51 |         29.98  |
|            52 |         30.18  |
|            53 |         36.92  |
|            54 |         37.12  |
|            55 |         30.27  |
|            56 |         37.78  |
|            57 |         36.3   |
|            58 |         32.36  |
|            59 |         20.408 |
|            60 |         25.05  |
|            61 |         29.578 |
|            62 |         36.4   |
|            63 |         23.033 |
|            64 |         36.52  |
|            65 |         38.72  |
|            66 |         30.475 |
|            67 |         30.35  |
|            68 |         26.359 |
|            69 |         29.27  |
|            70 |         40.25  |
|            71 |         23.528 |
|            72 |         41.72  |
|            73 |         29.59  |
|            74 |         28.83  |
|            75 |         35.72  |
|            76 |         24.47  |
|            77 |         34.2   |
|            78 |         44.15  |
|            79 |         30.86  |
|            80 |         32.42  |
|            81 |         29.2   |
|            82 |         50.13  |
|            83 |         45.39  |
|            84 |         27.65  |
|            85 |         36.98  |
|            86 |         35.94  |
|            87 |         43.61  |
|            88 |         34.16  |
|            89 |         29.88  |
|            90 |         38.64  |
|            91 |         38.13  |
|            92 |         28.03  |
|            93 |         31.75  |
|            94 |         34.89  |
|            95 |         43.29  |
|            96 |         30.02  |
|            97 |         29.727 |
|            98 |         24.44  |
|            99 |         34.19  |
|           100 |         38.59  |
|           101 |         20.411 |
|           102 |         32.7   |
|           103 |         29.276 |
|           104 |         29.78  |
|           105 |         28.67  |
|           106 |         29.97  |
|           107 |         30.9   |
|           108 |         41.94  |
|           109 |         32.6   |
|           110 |         26.767 |
|           111 |         33.39  |
|           112 |         33.91  |
|           113 |         30.7   |
|           114 |         24.556 |
|           115 |         33.46  |
|           116 |         24.71  |
|           117 |         31.54  |
|           118 |         38.69  |
|           119 |         37.96  |
|           120 |         22.23  |
|           121 |         35.78  |
|           122 |         44.45  |
|           123 |         25.39  |
|           124 |         29.76  |
|           125 |         31.06  |
|           126 |         38.3   |
|           127 |         37.91  |
|           128 |         31.49  |
|           129 |         44.91  |
|           130 |         25.48  |
|           131 |         34.94  |
|           132 |         37.7   |
|           133 |         29.64  |
|           134 |         40.36  |
|           135 |         35.24  |
|           136 |         28.38  |
|           137 |         26.82  |
|           138 |         32.52  |
|           139 |         24.67  |
|           140 |         21.708 |
|           141 |         34.16  |
|           142 |         28.74  |
|           143 |         28.82  |
|           144 |         25.72  |
|           145 |         26.55  |
|           146 |         28.38  |
|           147 |         33.72  |
|           148 |         29.62  |
|           149 |         31.65  |
|           150 |         33.78  |
|           151 |         28.919 |
|           152 |         25.071 |
|           153 |         24.23  |
|           154 |         28.49  |
|           155 |         30.19  |
|           156 |         38.42  |
|           157 |         36.3   |
|           158 |         24.8   |
|           159 |         23.86  |
|           160 |         31.93  |
|           161 |         35.13  |
|           162 |         37.74  |
|           163 |         34.56  |
|           164 |         45.31  |
|           165 |         34.73  |
|           166 |         20.51  |
|           167 |         35.58  |
|           168 |         42.15  |
|           169 |         31.92  |
|           170 |         24.71  |
|           171 |         33.06  |
|           172 |         27.35  |
|           173 |         25.79  |
|           174 |         25.81  |
|           175 |         23.121 |
|           176 |         27.964 |
|           177 |         36.57  |
|           178 |         35.23  |
|           179 |         25.87  |
|           180 |         49.09  |
|           181 |         47.66  |
|           182 |         36.01  |
|           183 |         26.33  |
|           184 |         37.69  |
|           185 |         25.19  |
|           186 |         36.89  |
|           187 |         28.9   |
|           188 |         29.2   |
|           189 |         28.2   |
|           190 |         37.34  |
|           191 |         34.18  |
|           192 |         27.94  |
|           193 |         39.2   |
|           194 |         38.07  |
|           195 |         29.24  |
|           196 |         36.06  |
|           197 |         39.92  |
|           198 |         41.67  |
|           199 |         34.67  |
|           200 |         31.79  |
|           201 |         36.86  |
|           202 |         49.96  |
|           203 |         37.56  |
|           204 |         31.07  |
|           205 |         31.8   |
|           206 |         27.146 |
|           207 |         37.27  |
|           208 |         35.65  |
|           209 |         28.18  |
|           210 |         42.72  |
|           211 |         30.78  |
|           212 |         46.58  |
|           213 |         42.98  |
|           214 |         38     |
|           215 |         30.79  |
|           216 |         30.24  |
|           217 |         27.68  |
|           218 |         41.36  |
|           219 |         52     |
|           220 |         26.81  |
|           221 |         27.46  |
|           222 |         27.71  |
|           223 |         36     |
|           224 |         30.29  |
|           225 |         27.81  |
|           226 |         25.9   |
|           227 |         30.51  |
|           228 |         36.59  |
|           229 |         35.16  |
|           230 |         36.13  |
|           231 |         38.4   |
|           232 |         45.03  |
|           233 |         48.32  |
|           234 |         25.477 |
|           235 |         35.28  |
|           236 |         50.18  |
|           237 |         41.94  |
|           238 |         42.07  |
|           239 |         56.74  |
|           240 |         29.24  |
|           241 |         27.46  |
|           242 |         29.49  |
|           243 |         37.52  |
|           244 |         42.9   |
|           245 |         30.34  |
|           246 |         30.63  |
|           247 |         27     |
|           248 |         35.87  |
|           249 |         26.45  |
|           250 |         44.5   |
|           251 |         29.95  |
|           252 |         39.55  |
|           253 |         34.38  |
|           254 |         38.78  |
|           255 |         31.01  |
|           256 |         48.32  |
|           257 |         32.59  |
|           258 |         38.86  |
|           259 |         49.09  |
|           260 |         47.37  |
|           261 |         40.41  |
|           262 |         39.42  |
|           263 |         34.99  |
|           264 |         39.26  |
|           265 |         51.85  |
|           266 |         29.55  |
|           267 |         35.43  |
|           268 |         29.08  |
|           269 |         31.1   |
|           270 |         31.11  |
|           271 |         24.33  |
|           272 |         42.74  |
|           273 |         25.412 |
|           274 |         42.41  |
|           275 |         29.25  |
|           276 |         25.49  |
|           277 |         38.79  |
|           278 |         31.43  |
|           279 |         29.03  |
|           280 |         45.76  |
|           281 |         25.76  |
|           282 |         37.58  |
|           283 |         35.01  |
|           284 |         28.59  |
|           285 |         30.98  |
|           286 |         32.7   |
|           287 |         26.01  |
|           288 |         31.22  |
|           289 |         30.26  |
|           290 |         34.14  |
|           291 |         34.06  |
|           292 |         28.97  |
|           293 |         29.31  |
|           294 |         26.5   |
|           295 |         27.04  |
|           296 |         23.26  |
|           297 |         29.9   |
|           298 |         32.43  |
|           299 |         33.6   |
|           300 |         38.43  |
|           301 |         32.35  |
|           302 |         43.95  |
|           303 |         29.1   |
|           304 |         29.62  |
|           305 |         36.09  |
|           306 |         29.02  |
|           307 |         23.4   |
|           308 |         26.21  |
|           309 |         26.89  |
|           310 |         30.81  |
|           311 |         30.3   |
|           312 |         26.13  |
|           313 |         22.26  |
|           314 |         27.197 |
|           315 |         29.34  |
|           316 |         26.26  |
|           317 |         37.09  |
|           318 |         27.942 |
|           319 |         29.43  |
|           320 |         26.43  |
|           321 |         39.82  |
|           322 |         26.18  |
|           323 |         41.85  |
|           324 |         27.41  |
|           325 |         29.97  |
|           326 |         26.99  |
|           327 |         29.96  |
|           328 |         36.98  |
|           329 |         38.14  |
|           330 |         31.54  |
|           331 |         32.33  |
|           332 |         31.08  |
|           333 |         26.03  |
|           334 |         31.32  |
|           335 |         38.06  |
|           336 |         27.22  |
|           337 |         40.2   |
|           338 |         27.58  |
|           339 |         47.78  |
|           340 |         30.96  |
|           341 |         26.446 |
|           342 |         26.02  |
|           343 |         41.36  |
|           344 |         27.16  |
|           345 |         24.97  |
|           346 |         30.96  |
|           347 |         29.5   |
|           348 |         27.5   |
|           349 |         26.91  |
|           350 |         28.73  |
|           351 |         34.97  |
|           352 |         43.19  |
|           353 |         40.82  |
|           354 |         25.21  |
|           355 |         31.63  |
|           356 |         31.64  |
|           357 |         30.08  |
|           358 |         24.368 |
|           359 |         27.756 |
|           360 |         30.61  |
|           361 |         34.87  |
|           362 |         31.6   |
|           363 |         34.79  |
|           364 |         30.35  |
|           365 |         42.22  |
|           366 |         47.03  |
|           367 |         30.23  |
|           368 |         38.96  |
|           369 |         43.91  |
|           370 |         39.64  |
|           371 |         28.4   |
|           372 |         36.47  |
|           373 |         37.99  |
|           374 |         29.76  |
|           375 |         32.24  |
|           376 |         30.79  |
|           377 |         41.67  |
|           378 |         28.81  |
|           379 |         29.91  |
|           380 |         24.23  |
|           381 |         25.97  |
|           382 |         34.77  |
|           383 |         29.87  |
|           384 |         27     |
|           385 |         37.89  |
|           386 |         26.3   |
|           387 |         30.04  |
|           388 |         26.77  |
|           389 |         42.76  |
|           390 |         22.48  |
|           391 |         25.574 |
|           392 |         35.46  |
|           393 |         43.89  |
|           394 |         29.82  |
|           395 |         31.24  |
|           396 |         32.4   |
|           397 |         30.26  |
|           398 |         25.89  |
|           399 |         29.06  |
|           400 |         38.93  |
|           401 |         22.84  |
|           402 |         31.25  |
|           403 |         29.11  |
|           404 |         27.29  |
|           405 |         29.53  |
|           406 |         31     |
|           407 |         34.22  |
|           408 |         38.65  |
|           409 |         30.19  |
|           410 |         28.93  |
|           411 |         27.87  |
|           412 |         31.077 |
|           413 |         37.1   |
|           414 |         44.94  |
|           415 |         33.06  |
|           416 |         31.105 |
|           417 |         36.58  |
|           418 |         24.87  |
|           419 |         32.57  |
|           420 |         30.61  |
|           421 |         28.67  |
|           422 |         27.63  |
|           423 |         32.79  |
|           424 |         28.862 |
|           425 |         31.31  |
|           426 |         25.46  |
|           427 |         32.78  |
|           428 |         27.75  |
|           429 |         30.39  |
|           430 |         37.43  |
|           431 |         30.08  |
|           432 |         39.72  |
|           433 |         40.79  |
|           434 |         31.8   |
|           435 |         33.6   |
|           436 |         32.41  |
|           437 |         30.02  |
|           438 |         33.45  |
|           439 |         29.68  |
|           440 |         28.17  |
|           441 |         42.69  |
|           442 |         29.57  |
|           443 |         28.89  |
|           444 |         34.88  |
|           445 |         36.88  |
|           446 |         45.78  |
|           447 |         32.46  |
|           448 |         33.87  |
|           449 |         41.62  |
|           450 |         33.41  |
|           451 |         44.59  |
|           452 |         40.23  |
|           453 |         28.51  |
|           454 |         29.77  |
|           455 |         44.1   |
|           456 |         40.92  |
|           457 |         38.46  |
|           458 |         38.13  |
|           459 |         37.955 |
|           460 |         44.23  |
|           461 |         53.69  |
|           462 |         41.39  |
|           463 |         29.96  |
|           464 |         31.39  |
|           465 |         33.37  |
|           466 |         33.88  |
|           467 |         27.768 |
|           468 |         40.93  |
|           469 |         29.8   |
|           470 |         28.157 |
|           471 |         40.18  |
|           472 |         29.85  |
|           473 |         42.24  |
|           474 |         26.5   |
|           475 |         28.56  |
|           476 |         34.73  |
|           477 |         30.52  |
|           478 |         26.08  |
|           479 |         35.76  |
|           480 |         30.19  |
|           481 |         33.14  |
|           482 |         27.53  |
|           483 |         31.34  |
|           484 |         27.01  |
|           485 |         28.86  |
|           486 |         31.49  |
|           487 |         38.26  |
|           488 |         27.85  |
|           489 |         36.89  |
|           490 |         34.69  |
|           491 |         31.08  |
|           492 |         38.57  |
|           493 |         25.29  |
|           494 |         33.7   |
|           495 |         35.08  |
|           496 |         30.82  |
|           497 |         29.78  |
|           498 |         36.01  |
|           499 |         41.83  |
|           500 |         31.78  |
|           501 |         38.31  |
|           502 |         28.86  |
|           503 |         42.92  |
|           504 |         22.138 |
|           505 |         22.816 |
|           506 |         32.26  |
|           507 |         28.18  |
|           508 |         32     |
|           509 |         39.41  |
|           510 |         26.43  |
|           511 |         29.51  |
|           512 |         33.92  |
|           513 |         28.24  |
|           514 |         34.12  |
|           515 |         29.95  |
|           516 |         38.89  |
|           517 |         40.15  |
|           518 |         31.1   |
|           519 |         29.45  |
|           520 |         23.195 |
|           521 |         46.23  |
|           522 |         31.09  |
|           523 |         32.39  |
|           524 |         25.527 |
|           525 |         21.671 |
|           526 |         32.21  |
|           527 |         24.61  |
|           528 |         27.11  |
|           529 |         25.51  |
|           530 |         29.31  |
|           531 |         31.69  |
|           532 |         30.01  |
|           533 |         41.14  |
|           534 |         28.58  |
|           535 |         41.41  |
|           536 |         36.82  |
|           537 |         36.13  |
|           538 |         33.219 |
|           539 |         33.131 |
|           540 |         25.98  |
|           541 |         39.46  |
|           542 |         40.16  |
|           543 |         41.27  |
|           544 |         34.57  |
|           545 |         36.85  |
|           546 |         26.67  |
|           547 |         26.84  |
|           548 |         29.023 |
|           549 |         35.03  |
|           550 |         32.34  |
|           551 |         33.57  |
|           552 |         42.2   |
|           553 |         31.273 |
|           554 |         41.8   |
|           555 |         37.9   |
|           556 |         29.75  |
|           557 |         37.303 |
|           558 |         37.27  |
|           559 |         35.44  |
|           560 |         41.2   |
|           561 |         40.57  |
|           562 |         45.84  |
|           563 |         46.01  |
|           564 |         43.95  |
|           565 |         48.38  |
|           566 |         44.68  |
|           567 |         49.93  |
|           568 |         32.3   |